### ISSUE TITLE
My datasets problems

### ISSUE THREAD

**Issue by bobo18801737494** [safe-graph/DGFraud#30]
When I use the GEM algorithm of  DGFraud in my datasets, I have some problems with my datasets, 

1、my adj matrix is 720,000 X 720,000,how do i deal with it,sampling？if sampling may be lead to nodes and realationship broken?

2、My features is continuity numerical, for example the ages feature values is between 18 and 50， use directly or  binning processing ，one-hot encoding?

Looking forward to your reply。

**Comment by YingtongDou** [comment]
1. You can keep only a few informative neighbors under each relation. I don't know if such sampling could efficiently reduce the node size. Anyway, your sampling method should reduce the graph size while keeping enough neighbors for each node under each relation.

2. If you do not know how different encoding methods contribute to your classification task, you can test them using feature selection tools from sklearn and keep the simple and useful one. Or you can test them directly with GEM.
