### ISSUE TITLE
How did I use sparse matrix  as adj_list in GEM

### ISSUE THREAD

**Issue by bobo18801737494** [safe-graph/DGFraud#32]
When I use the GEM algorithm of DGFraud in my datasets, I try to  use sparse matrix as input adj_list, but it not work,
this is my code ,I dont know how to feed sparse tensor to the model,can you help me ? 
      
```
for d in range(self.devices_num):
            indices = np.mat([self.placeholders['a'][d].row, self.placeholders['a'][d].col]).transpose()
            m = tf.SparseTensor(indices, self.placeholders['a'][d].data, self.placeholders['a'][d].shape)
            with tf.Session as session:
                ah = session.run(tf.nn.embedding_lookup_sparse(input, m,None,combiner='sum'))
            
            ahv = tf.matmul(ah, self.vars['V'])
            h2.append(ahv)
```

**Comment by YingtongDou** [comment]
You can use the [tf.sparse.sparse_dense_matmul](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/sparse/sparse_dense_matmul) to directly multiply the sparse adjacency matrix ```self.placeholders['a'][d]``` and the initial node embeddings ```h```.
