### ISSUE TITLE
About semignn 

### ISSUE THREAD

**Issue by bobo18801737494** [safe-graph/DGFraud#33]
Hello,when I use semignn test my model,The following error occurred:

`ResourceExhaustedError: OOM when allocating tensor with shape[26656,213248] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu`

`   u_i_embedding = tf.nn.embedding_lookup(a_u, tf.cast(self.placeholders['u_i'], dtype=tf.int32))`
` u_j_embedding = tf.nn.embedding_lookup(a_u, tf.cast(self.placeholders['u_j'], dtype=tf.int32))`
`inner_product = tf.reduce_sum(u_i_embedding * u_j_embedding, axis=1)`

I debug this , found u_i, u_j  shape (213248，) may be the reason,when we use u_i, u_j compute loss2 , inner_product shape（26656，213248） so big ,it will cause the memory overflow 。 I only have 6664 nodes, 8 views, but I compute the loss2 with inner_product so big that program not continues.

Can you give me some help ?

**Comment by YingtongDou** [comment]
Since SemiGNN has multiple attention and loss computations, you'd better run your code on GPUs with larger memory.

Another solution is to run your data with minibatch. Currently, our code does not support minibatch training, we will fix it in the future version.
