### ISSUE TITLE
SemiGNN

### ISSUE THREAD

**Issue by wangtsiao** [safe-graph/DGFraud#35]
**SemiGNN中半监督学习Loss函数问题**
https://github.com/safe-graph/DGFraud/blob/master/algorithms/SemiGNN/SemiGNN.py#L119
在loss2函数中，代码好像没有实现负采样。
> Q is the number of nagative samples set to 3 in this paper.

**Comment by YingtongDou** [comment]
Thanks for your question.

The [negative sampling](https://github.com/safe-graph/DGFraud/blob/8d43fd23d700d7f176dc199e624bd5a1bb945ef6/algorithms/SemiGNN/SemiGNN_main.py#L82) is performed in the main function.

We would add it to the forward function of SemiGNN in the future version to make it more clear.
