### ISSUE TITLE
GAS Dataset

### ISSUE THREAD

**Issue by mjk-hub** [safe-graph/DGFraud#37]
In the dataset used for [GAS ](https://github.com/safe-graph/DGFraud/blob/master/utils/data_loader.py#L113), how are the **`review_vecs`** [[Line 128](https://github.com/safe-graph/DGFraud/blob/master/utils/data_loader.py#L128)] , **`homo_adj `**(Comment Graph) [[Line 149](https://github.com/safe-graph/DGFraud/blob/master/utils/data_loader.py#L149)] and **`y`** [[Line 159](https://github.com/safe-graph/DGFraud/blob/master/utils/data_loader.py#L159)] initialized?

**Comment by YingtongDou** [comment]
The above vectors and matrices are randomly initialized only for demonstration. You can initialize the feature, graph, and labels based on your datasets.
