### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by shaieesss** [safe-graph/DGFraud#39]
Amazon dataset, can you provide it? I can't find this dataset corresponding to the description in the paper

**Comment by YingtongDou** [comment]
Please find the old Amazon product data with helpfulness votes information [here](https://cseweb.ucsd.edu/~jmcauley/datasets.html#amazon_reviews). The original review texts are included in Amazon product datasets. You can download the review data of the ``Musical Instruments`` category from the above page and run the [amazon_preprocess.py](https://github.com/YingtongDou/CARE-GNN/blob/master/amazon_preprocess.py) to get the sampled 11,949 nodes and their corresponding features, or you can generate similar graphs using other review data from the Amazon dataset.
